live_config_reload = true
working_directory = "None"

# Themes --
import = [ 
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[window]
title = "Alacritty"
blur = true
opacity = 0.95
padding.x = 10
padding.y = 10
startup_mode = "Maximized"

[cursor.style]
shape= "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"


[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
